// Generated by CoffeeScript 1.7.1
(function() {
  importScripts('util.js');

  importScripts('lib/numeric-1.2.6.js');

  importScripts('mds.js');

  importScripts('gene-matrix.js');

  this.onmessage = function(ev) {
    var comp, dist_arr, msg, range;
    if (ev.data.init != null) {
      return this.matrix = GeneMatrix.from_hash(ev.data.init);
    } else if (ev.data.msg != null) {
      msg = ev.data.msg;
      if (msg.mds != null) {
        range = msg.mds;
        comp = MDS.pca_gene(this.matrix, range);
        return postMessage(comp);
      } else if (msg.dist != null) {
        range = msg.dist;
        dist_arr = Distance.distance(this.matrix, range);
        return postMessage(dist_arr);
      } else {
        return our_log("WORKER:  Unknown method:", msg);
      }
    } else {
      return our_log("WORKER:  Unknown message:", ev.data);
    }
  };

}).call(this);
